[tool.poetry]
name = "rh-tdd-workshop"
version = "0.1.0"
description = ""
authors = ["Mr. X <mrx@example.com>"]

[tool.poetry.dependencies]
python = "^3.12"

[tool.poetry.group.dev.dependencies]
flake8 = "^7.1.1"

