name: Deploy to GitHub Pages

on:
  push:
    branches:
      - 'feature/*'  # feature/*ブランチへのPushで起動

jobs:
  python-ci:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      
      - name: Install Utils
        run: sudo apt-get install -y make

      - name: Install Python dependencies
        run: |
          pip install poetry
          poetry config virtualenvs.create false
          poetry install

      - name: Run Unit Tests
        run: make python-test
      
      - name: Python Static Analyze
        run: |
          make python-static-analyze

  nodejs-ci:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      
      - name: Install Utils
        run: sudo apt-get install -y make

      - name: Install Node.js dependencies
        run: |
          npm install

      - name: HTML Static Analyze
        run: |
          make html-static-analyze

  deploy:
    runs-on: ubuntu-latest
    needs: [python-ci, nodejs-ci]

    steps:
      - name: Check out the repository
        uses: actions/checkout@v4

      - name: Build-Like Process
        run: |
          mkdir -p docs
          cp -r src/* docs/

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GH_PAGES_DEPLOY_TOKEN }}
          publish_dir: ./docs  # 生成されたファイルを公開ブランチへ
          publish_branch: gh-pages
