name: Deploy to GitHub Pages

on:
  push:
    branches:
      - '*'

jobs:
  python-ci:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      
      - name: Install Utils
        run: sudo apt-get install -y make

      - name: Install Python dependencies
        run: |
          pip install poetry
          poetry config virtualenvs.create false
          poetry install

      - name: Unit Tests
        run: make python-test-with-coverage
      
      - name: Flake8
        run: make flake8

      - name: Pylint
        run: make pylint

      - name: Mypy
        run: make mypy

      - name: Bandit
        run: make bandit
      
      - name: Ruff
        run: make ruff-extend

      - name: Black (Dry Run)
        run: make black-check

      - name: isort (Dry Run)
        run: make isort-check

  nodejs-ci:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      
      - name: Install Utils
        run: sudo apt-get install -y make

      - name: Install Node.js dependencies
        run: |
          npm install

      - name: htmlhint
        run: make htmlhint

      - name: markdownlint
        run: make markdownlint

      - name: npm-audit
        run: make npm-audit

  deploy:
    runs-on: ubuntu-latest
    needs: [python-ci, nodejs-ci]
    env:
      GH_PAGES_URL: "https://f-kana.github.io/rh-tdd-workshop/"
    steps:
      - name: Check out the repository
        uses: actions/checkout@v4

      - name: Set Deploy DateTime into index.html
        id: set-deploy-datetime
        run: |
          DEPLOY_DATETIME=$(TZ=Asia/Tokyo date '+%Y-%m-%d %H:%M:%S')
          echo "DEPLOY_DATETIME=$DEPLOY_DATETIME" >> $GITHUB_ENV
          echo "::set-output name=deploy_datetime::$DEPLOY_DATETIME"
          sed -i "s/{{DEPLOY_DATETIME}}/$DEPLOY_DATETIME/" src/index.html

      - name: Build-Like Process
        run: |
          mkdir -p docs
          cp -r src/* docs/

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GH_PAGES_DEPLOY_TOKEN }}
          publish_dir: ./docs
          publish_branch: gh-pages

      - name: Wait for GitHub Pages to deploy
        run: sleep 30  # デプロイが反映されるまで待機

      - name: Check if the page is up
        run: |
          STATUS_CODE=$(curl -o /dev/null -s -w "%{http_code}\n" $GH_PAGES_URL)
          if [ $STATUS_CODE -ne 200 ]; then
            echo "Page is not up. Status code: $STATUS_CODE"
            exit 1
          fi
          echo "Page is up. Status code: $STATUS_CODE"
    
      - name: Check if deploy datetime is updated
        run: |
          PAGE_CONTENT=$(curl -s ${{ env.GH_PAGES_URL }})
          if [[ $PAGE_CONTENT != *"${{ steps.set-deploy-datetime.outputs.deploy_datetime }}"* ]]; then
            echo "Deploy datetime is not updated."
            exit 1
          fi
          echo "Deploy seems to be successful."
